name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  
      - name: install dependencies
        working-directory: ./server
        run: npm install
          
  builddockerimage:

    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  generatedocs:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        working-directory: ./server
        run: npm install

      - name: Generate Documentation
        working-directory: ./server
        run: npx documentation build src/** -f html -o docs

      - name: Upload Docs Artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: ./server/docs